<h1 style="color:skyblue"><b>Importing<b></h1>

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from category_encoders import TargetEncoder

<h1 style="color:skyblue"><b>Generaing Random Dataset and spliting train test<b></h1>

In [39]:
np.random.seed(42)
n_rows = 1000

df = pd.DataFrame({
    "Col-1":np.random.choice(["A11","A12","A13","A14","A15","A16","A17","A11","A12"],n_rows),
    "Col-2":np.random.choice(["S","A","I","S","A","I","A","V","S"], n_rows),
    "Target":np.random.choice([100, 200, 400, 200, 500, 600, 500, 400, 800],n_rows),
    })

In [40]:
x = df.drop(columns="Target")
y = df.Target

Xtrain, Xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

---
---

<h1 style="color:skyblue"><b>Types of Encoding</b></h1>

---
---

<h1 style="color:lightgreen"><b>1. LabelEncoder</b></h1>

### **Working-**
        - selects unique columns
        - sort by acessding order
        - assigns values from 0
        - stores values in dictonary
ex:
        {
                "red":2,
                "c1":1,
                "c2":2,
        }



>### **Note - use only 1D array(Single column) | Error if more than 1 column**

In [41]:
Lable = LabelEncoder()
updated_Xtrain = Lable.fit_transform(Xtrain["Col-1"])
updated_Xtrain

# Lable.transform(Xtrain["Col-2"])    Error of unseen data

array([4, 5, 0, 2, 1, 2, 0, 6, 6, 1, 4, 2, 3, 0, 6, 4, 2, 0, 5, 4, 6, 0,
       1, 0, 3, 0, 0, 4, 2, 5, 1, 6, 6, 1, 1, 6, 0, 6, 6, 0, 4, 6, 0, 0,
       6, 6, 0, 2, 6, 6, 0, 6, 6, 0, 1, 2, 4, 0, 1, 2, 5, 3, 5, 0, 1, 0,
       1, 4, 2, 6, 0, 2, 0, 0, 4, 3, 0, 0, 2, 2, 4, 0, 1, 1, 0, 1, 1, 3,
       0, 1, 0, 1, 5, 1, 0, 4, 1, 4, 0, 0, 5, 4, 0, 0, 0, 5, 4, 5, 6, 6,
       4, 1, 2, 6, 0, 0, 0, 6, 2, 4, 0, 0, 0, 1, 3, 1, 0, 1, 0, 1, 5, 6,
       3, 1, 6, 0, 1, 1, 0, 0, 1, 2, 6, 6, 1, 4, 0, 5, 0, 5, 5, 4, 3, 0,
       5, 1, 0, 1, 5, 0, 3, 1, 6, 1, 0, 2, 3, 3, 0, 0, 5, 2, 0, 0, 6, 3,
       1, 0, 4, 0, 1, 1, 1, 1, 3, 4, 2, 3, 0, 2, 2, 1, 1, 2, 4, 1, 0, 6,
       1, 1, 2, 3, 1, 1, 0, 6, 1, 5, 1, 3, 0, 0, 4, 1, 4, 1, 1, 5, 5, 0,
       1, 0, 1, 0, 2, 2, 4, 1, 6, 0, 4, 0, 4, 2, 4, 2, 0, 2, 3, 5, 0, 1,
       0, 2, 3, 0, 3, 0, 2, 4, 5, 3, 6, 4, 3, 1, 0, 4, 4, 6, 0, 4, 4, 0,
       4, 4, 6, 1, 3, 1, 2, 6, 3, 1, 6, 2, 4, 1, 0, 4, 5, 4, 0, 3, 0, 6,
       3, 5, 1, 3, 4, 0, 5, 2, 1, 3, 1, 2, 5, 3, 1, 4, 0, 4, 3, 5, 0, 4,
       1, 2, 6, 6, 4, 1, 1, 3, 5, 1, 0, 1, 0, 1, 4, 2, 2, 5, 0, 1, 1, 0,
       5, 1, 1, 3, 2, 3, 0, 0, 4, 1, 2, 2, 1, 4, 6, 3, 2, 1, 4, 1, 3, 6,
       5, 1, 0, 3, 4, 4, 0, 6, 0, 2, 6, 4, 0, 6, 0, 5, 6, 2, 3, 3, 1, 3,
       1, 4, 0, 1, 2, 5, 1, 4, 1, 1, 1, 0, 2, 4, 1, 5, 3, 0, 2, 3, 5, 4,
       0, 3, 0, 5, 5, 6, 5, 2, 5, 0, 2, 6, 4, 1, 5, 0, 3, 6, 5, 0, 1, 0,
       0, 2, 0, 0, 2, 3, 0, 0, 1, 2, 0, 1, 0, 5, 0, 3, 3, 0, 3, 0, 6, 4,
       4, 3, 1, 6, 3, 6, 0, 6, 2, 4, 1, 0, 3, 2, 0, 0, 1, 2, 6, 6, 2, 6,
       1, 0, 3, 3, 0, 0, 1, 3, 2, 0, 5, 5, 5, 5, 1, 4, 4, 1, 0, 0, 0, 4,
       0, 3, 2, 4, 0, 1, 0, 0, 2, 3, 1, 5, 5, 6, 0, 6, 4, 0, 6, 3, 5, 5,
       0, 3, 1, 1, 4, 3, 2, 2, 5, 3, 5, 3, 6, 5, 3, 6, 1, 0, 0, 0, 4, 1,
       1, 0, 0, 1, 5, 2, 1, 0, 5, 0, 0, 2, 0, 4, 5, 5, 2, 4, 1, 0, 4, 2,
       6, 0, 5, 3, 1, 1, 0, 4, 0, 1, 3, 3, 3, 5, 0, 1, 0, 2, 0, 2, 5, 4,
       2, 4, 1, 0, 6, 5, 5, 6, 5, 1, 2, 4, 3, 0, 6, 5, 4, 0, 2, 2, 2, 1,
       0, 6, 3, 0, 0, 2, 3, 0, 0, 4, 1, 1, 2, 1, 4, 1, 0, 6, 1, 0, 3, 5,
       5, 1, 2, 1, 5, 5, 4, 2, 2, 1, 0, 6, 0, 0, 0, 1, 5, 2, 6, 0, 3, 2,
       2, 0, 0, 0, 5, 2, 4, 0, 0, 0, 6, 3, 4, 0, 6, 0, 2, 1, 2, 5, 2, 5,
       3, 2, 6, 5, 3, 6, 3, 1, 0, 6, 0, 0, 1, 5, 0, 0, 1, 0, 4, 0, 4, 5,
       0, 3, 0, 1, 0, 5, 1, 3, 1, 2, 1, 1, 6, 6, 0, 4, 1, 0, 0, 6, 2, 1,
       5, 4, 1, 0, 1, 6, 4, 5, 6, 1, 0, 3, 0, 3, 4, 2, 2, 6, 3, 0, 3, 3,
       6, 6, 3, 4, 0, 2, 0, 2, 5, 0, 0, 2, 0, 2, 1, 6, 3, 2, 1, 5, 6, 2,
       3, 4, 0, 1, 3, 2, 3, 6, 2, 1, 6, 3, 4, 2, 6, 6, 2, 5, 3, 3, 1, 2,
       3, 3, 1, 1, 0, 0, 3, 2, 1, 3, 1, 1, 3, 0, 4, 1, 6, 5, 6, 4, 1, 0,
       0, 2, 6, 6, 3, 0, 1, 2])

---

<h1 style="color:lightgreen"><b>2. OneHotEncoder</b></h1>

### **Working-**
        - it encodes binary values
        - selects unique columns
        - sort by acessding order
        - creates columns based on unique values
        
        

><h3 style="color:orange"><b>Note - use only 2D array(more than 1 column) | Error if less than 2 column</b></h3>

<h3 style="color:#00FFFF">Important</h3>

        - it will return in the form of matrix
        - it will create more columns (columns of unique values)

---
<h3 style="color:#00FFFF"><pre><b>     Method - 1</b></pre></h3>

            - OneHot = OneHotEncoder()   # default sparse_output=True
            - in this method we  need to convert martix to read values

In [42]:
OneHot = OneHotEncoder()


updated_Xtrain = OneHot.fit_transform(Xtrain)

# toarray() => this will return values
values = updated_Xtrain.toarray()
values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 1., 0.]], shape=(800, 11))

In [43]:
# this will give column names(asc order)
colums = OneHot.get_feature_names_out()
colums

array(['Col-1_A11', 'Col-1_A12', 'Col-1_A13', 'Col-1_A14', 'Col-1_A15',
       'Col-1_A16', 'Col-1_A17', 'Col-2_A', 'Col-2_I', 'Col-2_S',
       'Col-2_V'], dtype=object)

In [44]:
# turning raw matrix into dataframe
pd.DataFrame(values, columns=colums)

,Col-1_A11,Col-1_A12,Col-1_A13,Col-1_A14,Col-1_A15,Col-1_A16,Col-1_A17,Col-2_A,Col-2_I,Col-2_S,Col-2_V
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
796,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
797,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
798,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
799,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

---
<h3 style="color:#00FFFF"><pre><b>     Method - 2</b></pre></h3>

            - OneHot = OneHotEncoder(sparse_output=False)
            - in this method we dont need to convert to array
            - directly we can get array
            - use this method for projects and further

In [45]:
# Default value for handle_unknown is error change to ignore it will  
OneHot = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

updated_Xtrain = OneHot.fit_transform(Xtrain)
updated_Xtrain

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 1., 0.]], shape=(800, 11))

In [46]:

OneHot.transform([["X11","M"]])

c:\Users\MAYURESHWAR\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
pd.DataFrame(updated_Xtrain,columns=colums)

,Col-1_A11,Col-1_A12,Col-1_A13,Col-1_A14,Col-1_A15,Col-1_A16,Col-1_A17,Col-2_A,Col-2_I,Col-2_S,Col-2_V
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
796,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
797,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
798,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
799,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

---
<h3 style="color:#00FFFF"><pre><b>     Continuation with Transform</b></pre></h3>

In [48]:
OneHot.transform(Xtrain["Col-1"]) # need to send 2-d

ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [ ]:
OneHot.transform(Xtest)  # valid why? xtest is 2-D

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 0., 0.]], shape=(200, 11))

In [ ]:
# OneHot.transform([["A11"],["S"]]) # Invalid syntax

# One column 2 rows
pd.DataFrame([["A11"],["S"]])

c:\Users\MAYURESHWAR\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

     0
0  A11
1    S

In [ ]:
OneHot.transform([["A11"]]) # Invalid syntax (columns used in fit must be same size as transform)
# Before we have given 2 columns and now 1 column will give error

c:\Users\MAYURESHWAR\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

ValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.

In [ ]:
OneHot.transform([["A11","S"]]) # Valid values were previously used in fit

c:\Users\MAYURESHWAR\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [ ]:
OneHot.transform([["C11","M"]]) # unknown columns values (it is not give at time of fit)

c:\Users\MAYURESHWAR\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories ['C11'] in column 0 during transform

In [ ]:
OneHot.transform([["c11","m"]])
# it will all zero becaues those values never exist in fit

c:\Users\MAYURESHWAR\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

---

<h1 style="color:lightgreen"><b>3. Ordinal Encoder</b></h1>


## **Working**
    - works for 1 column also
    - it will make a dictory and assing values accordingly starting from 0
    - works like lable encoder when order not specified
    - selects unique values and arranges as given order 
    - assigns values from 0

><h3 style="color:orange"><b>Note - it works for 1 column also and it gives random values if order not passed(Lable encoder)</b></h3>


## **Import**
    -from sklearn.preprocessing import OrdinalEncoder

## **unknown values**
    - it dont have handle_unknown="ignore"
    - we use handle_unknown="use_encoded_value", unknown_value=-1 while creating obj
    - here we assign -1 to unknown not 0 because the values assigment starts from 0 to inf
    - if we use 0 or any other +ve values it will mix the values and will get wrong values

---
<h3 style="color:#00FFFF"><pre><b>     Method - 1</b></pre></h3>

In [ ]:
Ord = OrdinalEncoder() # creating Obj

In [ ]:
updated_Xtrain = Ord.fit_transform(Xtrain) # only 2-D array
updated_Xtrain

array([[4., 0.],
       [5., 1.],
       [0., 0.],
       ...,
       [0., 2.],
       [1., 3.],
       [2., 2.]], shape=(800, 2))

In [ ]:
updated_Xtest = Ord.transform(Xtest) # only 2-D ande error when used 1D
updated_Xtest

array([[4., 1.],
       [1., 2.],
       [5., 1.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [1., 3.],
       [1., 0.],
       [5., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [4., 1.],
       [0., 1.],
       [4., 2.],
       [5., 1.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [1., 2.],
       [2., 0.],
       [1., 3.],
       [2., 0.],
       [4., 2.],
       [6., 0.],
       [1., 2.],
       [0., 3.],
       [0., 2.],
       [4., 1.],
       [4., 2.],
       [5., 0.],
       [5., 1.],
       [1., 0.],
       [0., 2.],
       [6., 0.],
       [0., 0.],
       [0., 2.],
       [3., 0.],
       [0., 0.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [2., 0.],
       [6., 2.],
       [0., 3.],
       [5., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [4., 1.],
       [5., 0.],
       [3., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [4., 0.],
       [1., 0.],
       [3., 0.],
       [2., 2.],
       [4., 0.],
       [2., 3.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [5., 1.],
       [2., 2.],
       [0., 0.],
       [0., 0.],
       [5., 2.],
       [1., 0.],
       [6., 0.],
       [4., 1.],
       [6., 2.],
       [1., 1.],
       [4., 2.],
       [0., 0.],
       [5., 0.],
       [5., 2.],
       [5., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [5., 2.],
       [0., 0.],
       [4., 1.],
       [1., 1.],
       [3., 0.],
       [4., 2.],
       [1., 1.],
       [5., 0.],
       [5., 0.],
       [0., 2.],
       [0., 2.],
       [5., 2.],
       [4., 0.],
       [5., 2.],
       [3., 0.],
       [3., 1.],
       [6., 0.],
       [1., 0.],
       [6., 0.],
       [0., 2.],
       [5., 0.],
       [0., 1.],
       [4., 1.],
       [0., 0.],
       [1., 0.],
       [4., 2.],
       [5., 2.],
       [5., 2.],
       [1., 3.],
       [1., 2.],
       [4., 0.],
       [2., 2.],
       [4., 0.],
       [5., 1.],
       [1., 1.],
       [2., 0.],
       [4., 0.],
       [0., 0.],
       [1., 2.],
       [5., 2.],
       [1., 2.],
       [1., 0.],
       [6., 0.],
       [1., 2.],
       [0., 0.],
       [4., 1.],
       [1., 0.],
       [4., 2.],
       [0., 2.],
       [6., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [6., 1.],
       [0., 3.],
       [0., 2.],
       [5., 0.],
       [1., 0.],
       [1., 0.],
       [4., 0.],
       [1., 3.],
       [0., 0.],
       [6., 0.],
       [3., 0.],
       [4., 2.],
       [1., 2.],
       [1., 0.],
       [5., 0.],
       [5., 0.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [3., 2.],
       [0., 1.],
       [4., 0.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [4., 0.],
       [6., 1.],
       [0., 1.],
       [5., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [4., 0.],
       [6., 1.],
       [2., 2.],
       [6., 2.],
       [0., 0.],
       [0., 3.],
       [5., 0.],
       [6., 1.],
       [6., 1.],
       [0., 2.],
       [6., 0.],
       [6., 2.],
       [0., 0.],
       [4., 0.],
       [1., 1.],
       [0., 2.],
       [3., 0.],
       [1., 2.],
       [0., 1.]])

In [ ]:
# new input

new_input = [["AVC","ADF"]]

Ord.transform(new_input) # unknown values will through error

c:\Users\MAYURESHWAR\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories ['AVC'] in column 0 during transform

---
<h3 style="color:#00FFFF"><pre><b>     Method - 2</b></pre></h3>

In [ ]:
Ord = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)

In [ ]:
Ord.fit_transform(Xtrain)

array([[4., 0.],
       [5., 1.],
       [0., 0.],
       ...,
       [0., 2.],
       [1., 3.],
       [2., 2.]], shape=(800, 2))

In [ ]:
Ord.transform(Xtest)

array([[4., 1.],
       [1., 2.],
       [5., 1.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [1., 3.],
       [1., 0.],
       [5., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [4., 1.],
       [0., 1.],
       [4., 2.],
       [5., 1.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [1., 2.],
       [2., 0.],
       [1., 3.],
       [2., 0.],
       [4., 2.],
       [6., 0.],
       [1., 2.],
       [0., 3.],
       [0., 2.],
       [4., 1.],
       [4., 2.],
       [5., 0.],
       [5., 1.],
       [1., 0.],
       [0., 2.],
       [6., 0.],
       [0., 0.],
       [0., 2.],
       [3., 0.],
       [0., 0.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [2., 0.],
       [6., 2.],
       [0., 3.],
       [5., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [4., 1.],
       [5., 0.],
       [3., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [4., 0.],
       [1., 0.],
       [3., 0.],
       [2., 2.],
       [4., 0.],
       [2., 3.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [5., 1.],
       [2., 2.],
       [0., 0.],
       [0., 0.],
       [5., 2.],
       [1., 0.],
       [6., 0.],
       [4., 1.],
       [6., 2.],
       [1., 1.],
       [4., 2.],
       [0., 0.],
       [5., 0.],
       [5., 2.],
       [5., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [5., 2.],
       [0., 0.],
       [4., 1.],
       [1., 1.],
       [3., 0.],
       [4., 2.],
       [1., 1.],
       [5., 0.],
       [5., 0.],
       [0., 2.],
       [0., 2.],
       [5., 2.],
       [4., 0.],
       [5., 2.],
       [3., 0.],
       [3., 1.],
       [6., 0.],
       [1., 0.],
       [6., 0.],
       [0., 2.],
       [5., 0.],
       [0., 1.],
       [4., 1.],
       [0., 0.],
       [1., 0.],
       [4., 2.],
       [5., 2.],
       [5., 2.],
       [1., 3.],
       [1., 2.],
       [4., 0.],
       [2., 2.],
       [4., 0.],
       [5., 1.],
       [1., 1.],
       [2., 0.],
       [4., 0.],
       [0., 0.],
       [1., 2.],
       [5., 2.],
       [1., 2.],
       [1., 0.],
       [6., 0.],
       [1., 2.],
       [0., 0.],
       [4., 1.],
       [1., 0.],
       [4., 2.],
       [0., 2.],
       [6., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [6., 1.],
       [0., 3.],
       [0., 2.],
       [5., 0.],
       [1., 0.],
       [1., 0.],
       [4., 0.],
       [1., 3.],
       [0., 0.],
       [6., 0.],
       [3., 0.],
       [4., 2.],
       [1., 2.],
       [1., 0.],
       [5., 0.],
       [5., 0.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [3., 2.],
       [0., 1.],
       [4., 0.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [4., 0.],
       [6., 1.],
       [0., 1.],
       [5., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [4., 0.],
       [6., 1.],
       [2., 2.],
       [6., 2.],
       [0., 0.],
       [0., 3.],
       [5., 0.],
       [6., 1.],
       [6., 1.],
       [0., 2.],
       [6., 0.],
       [6., 2.],
       [0., 0.],
       [4., 0.],
       [1., 1.],
       [0., 2.],
       [3., 0.],
       [1., 2.],
       [0., 1.]])

In [ ]:
Ord.transform(new_input) # now it will return -1 for unknown value

c:\Users\MAYURESHWAR\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1., -1.]])

In [ ]:
new_data = pd.DataFrame(data=[["A11","A12"],["S","V"]], columns=[["col-1","col-2"]])

# Ord.transform(new_data)

df

    Col-1 Col-2  Target
0     A17     V     100
1     A14     A     500
2     A11     V     200
3     A15     I     500
4     A17     S     500
..    ...   ...     ...
995   A11     A     200
996   A11     A     400
997   A12     S     400
998   A17     S     100
999   A13     I     600

[1000 rows x 3 columns]

><p><span style="color:#00FFFF">encoders = OrdinalEncoder(Categories=[["green","blue","red"]], handle_unknown="use_encoded_value", unknown_value=-1)</span>in categories we are providing order</p>

><p><span style="color:#00FFFF">encode.fit_transform(Xtrain)</span> => color | Size | material => 3-columns</p>

handle_unknown="use_encoded_value", orders for color column and (size & material) columns order is not mentioned shape of 
Xtrain is (800,3) 
               ^
            ___|
           | so mismatching value Error
categories(1, 3)
           |
           row order

><p><span style="color:#00FFFF">encoders = OrdinalEncoder(Categories=[["green","blue","red"],[""],[""]], handle_unknown="use_encoded_value", unknown_value=-1)</span>Fixed</p>

In [ ]:
Ord = OrdinalEncoder(categories=[["A17","A14","A15"]], handle_unknown="use_encoded_value", unknown_value=-1)

Ord.fit_transform(Xtrain[["Col-1"]])

array([[ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 2.],
       [-1.],
       [ 1.],
       [-1.],
       [ 0.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 2.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 0.],
       [ 0.],
       [ 2.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 2.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 0.],
       [-1.],
       [ 2.],
       [-1.],
       [ 2.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 1.],
       [ 0.],
       [ 2.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 2.],
       [ 0.],
       [-1.],
       [ 2.],
       [ 2.],
       [-1.],
       [ 2.],
       [ 2.],
       [ 0.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 2.],
       [-1.],
       [ 1.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 2.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [ 2.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 2.],
       [ 2.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 2.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 0.],
       [ 2.],
       [ 2.],
       [ 1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [-1.],
       [ 0.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 0.],
       [ 2.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 0.],
       [-1.],
       [ 1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [ 1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [-1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 2.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [ 1.],
       [ 2.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [-1.],
       [ 0.],
       [ 0.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 2.],
       [-1.],
       [ 0.],
       [-1.],
       [ 0.],
       [ 2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.]])

In [ ]:
Ord = OrdinalEncoder(categories=[["A17","A14","A15"],["V","A","S"]], handle_unknown="use_encoded_value", unknown_value=-1)

Ord.fit_transform(Xtrain)

array([[ 2.,  1.],
       [-1., -1.],
       [-1.,  1.],
       ...,
       [-1.,  2.],
       [-1.,  0.],
       [-1.,  2.]], shape=(800, 2))

---

<h1 style="color:lightgreen"><b>4. Target Encoder</b></h1>




### **Defination-** 
        - it is a encoding pre-processing technique which encodes the values based on target column, 
        - if the target column is continuse values then it takes avg() 
        - if the target column is categroical values then it takes majoritys

### **Importing Sytax-**
        from category_encoders import TargetEncodes
        encodes = TargetEncodes() # creating obj
        encodes.fit_transform(Xtrain, ytrain)  # Train the data
        encodes.transform(Xtest)               # Transform the data directly

### **Working-**

|col-1|col-2|Target|
|---|---|---|
|S|A1|100|
|I|A1|200|
|V|A2|50|
|V|A2|300|

        Step-1 :- Groups the unique values 
| | | | |     
|---|---|--|--|
|S|100|A1|100, 200|
|I|200|A2|50,30|
|V|50,300|


        Step 2 :- 
| | | | |     
|---|---|--|--|
|S|100|A1|150|
|I|200|A2|175|
|V|175|

        Step - 3:-
| Col-1|Col-2 |     
|---|---|
|100|150|
|200|150|
|175|175|
|175|175|


### **When to Use-**
        - when we have more unique values

><h3 style="color:orange"><b>Note - cols=[column names] => used to get specic columns to feed it and rest will remane same </b></h3>


TargetEncoder(cols=["Col-1"], handle_unknown="values")
              
>cols=["Col-1"] => only selected columns are transformed

>handle_unknown="values" => it will assign avg of all the values from target column

In [65]:
Target = TargetEncoder(cols=["Col-1"], handle_unknown="values")

In [68]:
updated_Xtrain = Target.fit_transform(Xtrain,ytrain)
updated_Xtrain

          Col-1 Col-2
29   438.169449     A
535  392.621757     I
695  435.204081     A
557  380.205736     I
836  406.711407     S
..          ...   ...
106  380.023346     I
270  374.487118     I
860  435.204081     S
435  406.711407     V
102  380.205736     S

[800 rows x 2 columns]

In [69]:
updated_Xtest = Target.transform(Xtest)
updated_Xtest

          Col-1 Col-2
521  438.169449     I
737  406.711407     S
740  392.621757     I
660  435.204081     A
411  380.205736     A
..          ...   ...
408  406.711407     I
332  435.204081     S
208  374.487118     A
613  406.711407     S
78   435.204081     I

[200 rows x 2 columns]

In [70]:
Xtrain.select_dtypes(include="object").columns
# to get column names according to their datatypes

C:\Users\MAYURESHWAR\AppData\Local\Temp\ipykernel_14072\92236950.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Xtrain.select_dtypes(include="object").columns

Index(['Col-1', 'Col-2'], dtype='str')

In [71]:
new_input = [["Z11","M"]]
Target.transform(new_input)

KeyError: 'Col-1'

#### **use this method when giving a new input**

In [73]:
new_input = pd.DataFrame({"Col-1":["Z11"],"Col-2":["M"]})
Target.transform(new_input)

   Col-1 Col-2
0    NaN     M